### PR TITLE
[FIX] Correct documentation

### PR DESCRIPTION
**Pull request by antonag32**
t-if="False" does not make an element invisible, but instead stops it from rendering, this error appeared on lint messages and has been corrected.

### CODE REVIEW

**Comment by antonag32** [comment]
cc @luisg123v

**Comment by antonag32** [comment]
@moylop260 I think the CI error may have to do with the version of argparse used, since the inconsistency  occurs in the string generated by  `--help` :thinking: . I tried running it on a docker container with the image `python:3.10.9-bullseye` and got the same behavior as locally. `argparse.__version__` in my case shows as 1.1.

**Comment by moylop260** [comment]
> @moylop260 I think the CI error may have to do with the version of argparse used, since the inconsistency occurs in the string generated by `--help` 🤔 . I tried running it on a docker container with the image `python:3.10.9-bullseye` and got the same behavior as locally. `argparse.__version__` in my case shows as 1.1.

You need to get the package info from the virtualenv generated from `tox`

I mean, after run
`tox -e update-readme`

Get the packages and versions using:
`source ~/odoo/odoo-pre-commit-hooks/.tox/update-readme/bin/activate && pip freeze && python -c "import argparse;print('argparse==%s' % argparse.__version__)" && python --version`

The output in my local is the following:
```txt
attrs==22.2.0
bleach==6.0.0
build==0.10.0
bump2version==1.0.1
cachetools==5.3.0
certifi==2022.12.7
cfgv==3.3.1
chardet==5.1.0
charset-normalizer==3.0.1
colorama==0.4.6
coverage==7.1.0
distlib==0.3.6
docutils==0.19
exceptiongroup==1.1.0
execnet==1.9.0
filelock==3.9.0
identify==2.5.15
idna==3.4
importlib-metadata==6.0.0
iniconfig==2.0.0
jaraco.classes==3.2.3
keyring==23.13.1
lxml==4.9.2
markdown-it-py==2.1.0
mdurl==0.1.2
more-itertools==9.0.0
nodeenv==1.7.0
oca-odoo-pre-commit-hooks @ file:///Users/moylop260/odoo/odoo-pre-commit-hooks/.tox/.tmp/package/2/oca_odoo_pre_commit_hooks-0.0.22-0.editable-py3-none-any.whl
packaging==23.0
pbr==5.11.1
pkginfo==1.9.6
platformdirs==2.6.2
pluggy==1.0.0
polib==1.1.1
pre-commit==3.0.0
Pygments==2.14.0
pyproject_api==1.5.0
pyproject_hooks==1.0.0
pytest==7.2.1
pytest-cov==4.0.0
pytest-xdist==3.1.0
PyYAML==6.0
readme-renderer==37.3
requests==2.28.2
requests-toolbelt==0.10.1
rfc3986==2.0.0
rich==13.2.0
six==1.16.0
tomli==2.0.1
tox==4.3.5
twine==4.0.2
urllib3==1.26.14
virtualenv==20.17.1
webencodings==0.5.1
zipp==3.11.0
argparse==1.1
Python 3.10.9
```

Could you run the same command and share the diff, please?

**Comment by antonag32** [comment]
@moylop260 

```
attrs==22.2.0
bleach==6.0.0
build==0.10.0
bump2version==1.0.1
cachetools==5.3.0
certifi==2022.12.7
cffi==1.15.1
cfgv==3.3.1
chardet==5.1.0
charset-normalizer==3.0.1
colorama==0.4.6
coverage==7.1.0
cryptography==39.0.0
distlib==0.3.6
docutils==0.19
exceptiongroup==1.1.0
execnet==1.9.0
filelock==3.9.0
identify==2.5.15
idna==3.4
importlib-metadata==6.0.0
iniconfig==2.0.0
jaraco.classes==3.2.3
jeepney==0.8.0
keyring==23.13.1
lxml==4.9.2
markdown-it-py==2.1.0
mdurl==0.1.2
more-itertools==9.0.0
nodeenv==1.7.0
oca-odoo-pre-commit-hooks @ file:///odoo-pre-commit-hooks/.tox/.tmp/package/1/oca_odoo_pre_commit_hooks-0.0.23-0.editable-py3-none-any.whl
packaging==23.0
pbr==5.11.1
pkginfo==1.9.6
platformdirs==2.6.2
pluggy==1.0.0
polib==1.1.1
pre-commit==3.0.1
pycparser==2.21
Pygments==2.14.0
pyproject_api==1.5.0
pyproject_hooks==1.0.0
pytest==7.2.1
pytest-cov==4.0.0
pytest-xdist==3.1.0
PyYAML==6.0
readme-renderer==37.3
requests==2.28.2
requests-toolbelt==0.10.1
rfc3986==2.0.0
rich==13.2.0
SecretStorage==3.3.3
six==1.16.0
tomli==2.0.1
tox==4.4.2
twine==4.0.2
urllib3==1.26.14
virtualenv==20.17.1
webencodings==0.5.1
zipp==3.11.0
argparse==1.1
Python 3.10.9
```

The docker image has some extra libraries, the only changes  in common libraries are:

| Package | Your Version  | python3.10.9-bullseye |
| ------------ |------------------ |-------------------------------|
| pre-commit  | 3.0.0 | 3.0.1 | 
| tox | 4.3.5 | 4.4.2 |

**Comment by moylop260** [comment]
Maybe it time to...
 - https://github.com/OCA/odoo-pre-commit-hooks/blob/9b98ad491e257d1006bfcc06e2b173593132bad4/tests/test_checks.py#L93

**Comment by antonag32** [comment]
> Maybe it time to...
> 
> * https://github.com/OCA/odoo-pre-commit-hooks/blob/9b98ad491e257d1006bfcc06e2b173593132bad4/tests/test_checks.py#L93

Haha, yes probably. Although I would  personally propose the deletion  of the help message from the README. I think it is redundant since users can  run  it  themselves to get help  and it also takes away  from other important parts in the README, like the examples.

**Comment by moylop260** [comment]
I like the help in the readme since it can be read without installing even before to install it

It is similar to autoflake8:
  - https://github.com/PyCQA/autoflake#advanced-usage

Could you check how they are doing it, please?

About the examples, I think it is important to have the check and the example related with real code, so the user can see directly where is the error reported

**Comment by antonag32** [comment]
> I like the help in the readme since it can be read without installing even before to install it
> 
> It is similar to autoflake8:
> 
> * https://github.com/PyCQA/autoflake#advanced-usage
> 
> Could you check how are they doing it, please?
> 
> About the examples, I think it is important to have the check and the example related with real code, so the user can see directly where is the error reported

For the record, looking at the commit history I think they edit their README manually, there are no tests to auto generate it, here are some commits which make me think it is all manual:

https://github.com/PyCQA/autoflake/commit/2358c714d8b8cd6dc16559a6418b56c245ac8eac
https://github.com/PyCQA/autoflake/commit/9e2cb69d68b4b1eaff7bfbf2c55a69e696fd6462
https://github.com/PyCQA/autoflake/commit/b567334b9fc699fc169af0ad1ea0ff0fc017fbeb

**Pull request merged**
