### PR TITLE
Show the actual record ids on duplicate records

### PR DESCRIPTION
**Pull request by ivantodorovich**

### CODE REVIEW

**Comment by moylop260** [comment]
Thank you @ivantodorovich 

How can I see the message output?

I mean, the CI is not showing this text related to `info` section

In fact, I just realized that we are not showing any `info` section running pre-commit command

IMHO `info` should be showed

**Comment by ivantodorovich** [comment]
Hello!

This is what I mentioned here: https://github.com/OCA/odoo-pre-commit-hooks/pull/106#issuecomment-2325251532

> Honestly, the scenario that looks better and makes it easier to read is the one we don't print any extra information at all:
>
> image
>
> Which is actually similar to what ruff does. I'm starting to be more inclined to this option
> What do you think?


Naturally, we can switch to the other alternative, where we display them every time. Or perhaps think of a `--verbose` option to enable these messages.

**Comment by moylop260** [comment]
IMHO if we have the option to see the number of line where the item is duplicated we can use the terminal option to auto-open using ctrl+click

So, you don't need to use extra steps or extra search to realize where is the line duplicated

What do you think?

**Comment by moylop260** [comment]
@ivantodorovich 

Yes, you are right!

But it could have valid duplicated

e.g.
- demo vs data section
- noupdate=1 vs noupdate=0

IMHO if we remove the "manifest section" we are detecting so we need to show the real line instead in order to avoid confusion and issues related

Also, we could see this PR is working well with the whole message correct

Even it could be separated commit

**Comment by moylop260** [comment]
@ivantodorovich 

Let me know if you will continue showing the duplicated lines even if verbose is not enabled, please

**Comment by ivantodorovich** [comment]
I'll take care of it asap :)

**Pull request merged**
