### PR TITLE
Draft: [IMP] add xml-duplicate-template-id message

### LINKED ISSUE #28: duplicate-xml-record-id should also apply to template and probably others
in https://github.com/OCA/pylint-odoo/blob/master/pylint_odoo/checkers/modules_odoo.py#L499 we check if one record overwrites another. This function only operates on `record` nodes, while we have a bunch of other nodes like `template` which also create records and possibly overwrite each other.

I think we should add some other helper function that yields all record creating nodes and use that in this function, right?

### PR DESCRIPTION
**Pull request by antonag32**
Fixes #28.

This adds a new message for xml files which detects duplicate ids found in templates (<template> tag).

### CODE REVIEW

**Comment by antonag32** [comment]
@luisg123v @moylop260 

Can you review? I also wonder if we should separate XML ids based on their manifest section (data, assets or qweb)? It seems to me that they are still duplicate regardless of the section, I think only separating them based on no_update makes sense.

**Comment by antonag32** [comment]
I also wonder if this should apply for `<templates>` tags

**Comment by moylop260** [comment]
@luisg123v 

Please, review

**Comment by moylop260** [comment]
Could you rebase it, please?

**Comment by moylop260** [comment]
👍 

Should be it merged @antonag32 ?

**Comment by antonag32** [comment]
> 👍
> 
> Should be it merged @antonag32 ?

In theory it should be ready, I left it as draft since I don't know if `<templates>` should also be included in the check.

**Comment by moylop260** [comment]
> > 👍
> > Should be it merged @antonag32 ?
> 
> In theory it should be ready, I left it as draft since I don't know if `<templates>` should also be included in the check.

Merged, since the `templates` are related to `src/` folder instead of `data/` one

**Pull request merged**
