### PR TITLE
[IMP] adds a new checked for filenames

### PR DESCRIPTION
**Pull request by maneandrea**
It could be desirable to have a checker that only lints filenames themselves and not their contents.

In this commit we add one which is only verifying that the name does not contain spaces, with its obvious implications for OS compatibilities.

### CODE REVIEW

**Comment by maneandrea** [comment]
cc @moylop260 I set it as draft because I did not make many checks yet. But you can have a look in the meantime.

**Comment by antonag32** [comment]
I think this is natively supported by pre-commit:

https://pre-commit.com/index.html#fail

> A lightweight [language](https://pre-commit.com/index.html#hooks-language) to forbid files by filename. The fail language is especially useful for [local](https://pre-commit.com/index.html#repository-local-hooks) hooks.

**Comment by maneandrea** [comment]
Oh, good to know. I guess we should close this PR then.

**Comment by maneandrea** [comment]
Oh, good to know. I guess we should close this PR then...

**Pull request closed without merging**
